### ISSUE TITLE
[FEATURE] Choose type of Event reply between Random and Round Robin messages

### ISSUE THREAD

**Issue by Ealenn** [Ealenn/LarbinBot#3]
**Describe the solution you'd like**
Choose type of handle into YAML file.
If empty, default value.

**Additional context**
Example: 
```yaml
events:
  - name: 'join'
    type: 'random'
    messages: 
      - 'Less noise {{ Username }} is coming!'
      - 'Ah! We are talking about you {{ Username }} !'
  - name: 'raided'
    messages: 
      - 'Thanks to @{{ Username }} for this raid of {{ Viewers }} viewers !'
```
