### ISSUE TITLE
[FEATURE] Choose type of Scheduler between Random and Round Robin

### ISSUE THREAD

**Issue by Ealenn** [Ealenn/LarbinBot#4]
## Describe the solution you'd like
Choose type of handler into YAML file.
If empty, default value.

## Additional context
Example:

```yml
schedulers:
  - id: 'social'
    type: 'random'
    minutes: 10
    messages:
    - 'Follow me on Twitter https://twitter.com/example'
  - id: 'other'
    minutes: 5
    messages:
    - 'Text rolling 1'
    - 'Text rolling 2'
    - 'Text rolling 3'
```
